/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    categories: Category;
    collections: Collection;
    'catalog-attribute-definitions': CatalogAttributeDefinition;
    'catalog-attribute-options': CatalogAttributeOption;
    products: Product;
    'product-variants': ProductVariant;
    inventory: Inventory;
    'inventory-movements': InventoryMovement;
    customers: Customer;
    'customer-addresses': CustomerAddress;
    wishlists: Wishlist;
    'wishlist-items': WishlistItem;
    carts: Cart;
    'cart-items': CartItem;
    promotions: Promotion;
    coupons: Coupon;
    orders: Order;
    'order-items': OrderItem;
    'order-status-events': OrderStatusEvent;
    'inventory-reservations': InventoryReservation;
    'payment-attempts': PaymentAttempt;
    'payment-webhook-events': PaymentWebhookEvent;
    'coupon-redemptions': CouponRedemption;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    collections: {
      products: 'products';
    };
    products: {
      variants: 'product-variants';
    };
    'product-variants': {
      inventory: 'inventory';
    };
    wishlists: {
      items: 'wishlist-items';
    };
    carts: {
      items: 'cart-items';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'catalog-attribute-definitions': CatalogAttributeDefinitionsSelect<false> | CatalogAttributeDefinitionsSelect<true>;
    'catalog-attribute-options': CatalogAttributeOptionsSelect<false> | CatalogAttributeOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    'inventory-movements': InventoryMovementsSelect<false> | InventoryMovementsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-addresses': CustomerAddressesSelect<false> | CustomerAddressesSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    'wishlist-items': WishlistItemsSelect<false> | WishlistItemsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-items': CartItemsSelect<false> | CartItemsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-items': OrderItemsSelect<false> | OrderItemsSelect<true>;
    'order-status-events': OrderStatusEventsSelect<false> | OrderStatusEventsSelect<true>;
    'inventory-reservations': InventoryReservationsSelect<false> | InventoryReservationsSelect<true>;
    'payment-attempts': PaymentAttemptsSelect<false> | PaymentAttemptsSelect<true>;
    'payment-webhook-events': PaymentWebhookEventsSelect<false> | PaymentWebhookEventsSelect<true>;
    'coupon-redemptions': CouponRedemptionsSelect<false> | CouponRedemptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'shipping-settings': ShippingSetting;
  };
  globalsSelect: {
    'shipping-settings': ShippingSettingsSelect<false> | ShippingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  role: 'super_admin' | 'catalog_manager' | 'order_manager' | 'support';
  status: 'active' | 'disabled';
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  kind: 'product' | 'lifestyle' | 'editorial' | 'review' | 'other';
  photographerCredit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  description?: string | null;
  sortOrder?: number | null;
  isActive: boolean;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  heroImage?: (number | null) | Media;
  occasion?: ('wedding' | 'haldi' | 'mehendi' | 'diwali' | 'festive' | 'everyday' | 'gifting') | null;
  isPublished: boolean;
  sortOrder?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status: 'draft' | 'active' | 'archived';
  primaryCategory: number | Category;
  categories?: (number | Category)[] | null;
  collections?: (number | Collection)[] | null;
  jewelryDetails?: {
    brand?: string | null;
    material?: string | null;
    plating?: string | null;
    stoneType?: string | null;
  };
  styleTags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  occasions?:
    | {
        occasion: 'wedding' | 'haldi' | 'mehendi' | 'diwali' | 'festive' | 'everyday' | 'gifting';
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  careInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isReturnable: boolean;
  returnWindowDays?: number | null;
  weightGrams?: number | null;
  hsnCode?: string | null;
  taxClass?: ('standard' | 'exempt' | 'custom') | null;
  featuredImage?: (number | null) | Media;
  /**
   * Ordered product and variant imagery.
   */
  gallery?:
    | {
        image: number | Media;
        variant?: (number | null) | ProductVariant;
        caption?: string | null;
        sortOrder: number;
        id?: string | null;
      }[]
    | null;
  isFeatured: boolean;
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  variants?: {
    docs?: (number | ProductVariant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  product: number | Product;
  sku: string;
  optionSignature: string;
  sizeCode?: string | null;
  colorCode?: string | null;
  finishCode?: string | null;
  optionValues?:
    | {
        attribute: number | CatalogAttributeDefinition;
        option: number | CatalogAttributeOption;
        id?: string | null;
      }[]
    | null;
  pricePaise: number;
  compareAtPricePaise?: number | null;
  costPaise?: number | null;
  status: 'active' | 'inactive' | 'discontinued';
  barcode?: string | null;
  weightGrams?: number | null;
  image?: (number | null) | Media;
  maxPerOrder?: number | null;
  inventory?: {
    docs?: (number | Inventory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-attribute-definitions".
 */
export interface CatalogAttributeDefinition {
  id: number;
  name: string;
  code: string;
  scope: 'product' | 'variant';
  valueType: 'select' | 'multi_select' | 'text';
  filterable: boolean;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-attribute-options".
 */
export interface CatalogAttributeOption {
  id: number;
  attribute: number | CatalogAttributeDefinition;
  code: string;
  label: string;
  swatchHex?: string | null;
  sortOrder?: number | null;
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: number;
  variant: number | ProductVariant;
  onHand: number;
  reserved: number;
  available?: number | null;
  reorderPoint?: number | null;
  stockStatus: 'available' | 'out_of_stock' | 'paused';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements".
 */
export interface InventoryMovement {
  id: number;
  variant: number | ProductVariant;
  quantityDelta: number;
  reason: 'initial_stock' | 'manual_adjustment' | 'order_fulfilled' | 'order_cancelled' | 'return_restock' | 'damage';
  referenceType?: string | null;
  referenceId?: string | null;
  performedBy?: (number | null) | Admin;
  note?: string | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName?: string | null;
  phoneNumber?: string | null;
  phoneVerified: boolean;
  status: 'active' | 'suspended';
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses".
 */
export interface CustomerAddress {
  id: number;
  customer: number | Customer;
  recipientName: string;
  phoneNumber: string;
  line1: string;
  line2?: string | null;
  landmark?: string | null;
  city: string;
  stateCode:
    | 'AN'
    | 'AP'
    | 'AR'
    | 'AS'
    | 'BR'
    | 'CH'
    | 'CG'
    | 'DH'
    | 'DL'
    | 'GA'
    | 'GJ'
    | 'HP'
    | 'HR'
    | 'JH'
    | 'JK'
    | 'KA'
    | 'KL'
    | 'LA'
    | 'LD'
    | 'MH'
    | 'ML'
    | 'MN'
    | 'MP'
    | 'MZ'
    | 'NL'
    | 'OD'
    | 'PB'
    | 'PY'
    | 'RJ'
    | 'SK'
    | 'TN'
    | 'TR'
    | 'TS'
    | 'UK'
    | 'UP'
    | 'WB';
  pincode: string;
  countryCode: 'IN';
  addressType: 'home' | 'work' | 'other';
  isDefault: boolean;
  isActive: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  customer: number | Customer;
  name: string;
  items?: {
    docs?: (number | WishlistItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist-items".
 */
export interface WishlistItem {
  id: number;
  wishlist: number | Wishlist;
  product: number | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  customer: number | Customer;
  status: 'active' | 'converted' | 'abandoned' | 'expired';
  currency: 'INR';
  coupon?: (number | null) | Coupon;
  convertedOrder?: (number | null) | Order;
  items?: {
    docs?: (number | CartItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  description?: string | null;
  promotion: number | Promotion;
  status: 'active' | 'disabled';
  usageLimit?: number | null;
  perCustomerLimit?: number | null;
  minimumCartPaise?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  name: string;
  description?: string | null;
  discountType: 'percentage' | 'fixed';
  discountValue: number;
  maxDiscountPaise?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  status: 'draft' | 'active' | 'paused' | 'expired';
  applicableProducts?: (number | Product)[] | null;
  applicableCategories?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | Customer;
  cart?: (number | null) | Cart;
  idempotencyKey: string;
  requestHash: string;
  status:
    'pending_payment' | 'confirmed' | 'processing' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
  paymentStatus: 'unpaid' | 'pending' | 'paid' | 'partially_refunded' | 'refunded' | 'failed';
  fulfillmentStatus: 'unfulfilled' | 'partial' | 'fulfilled' | 'returned';
  paymentMethod: 'upi' | 'card' | 'netbanking' | 'wallet' | 'cod';
  currency: 'INR';
  itemsSubtotalPaise: number;
  discountPaise: number;
  shippingPaise: number;
  taxPaise: number;
  codFeePaise: number;
  grandTotalPaise: number;
  shippingAddressSnapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  billingAddressSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pricingBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  couponCodeSnapshot?: string | null;
  customerNote?: string | null;
  exceptionCode?: string | null;
  placedAt: string;
  confirmedAt?: string | null;
  cancelledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items".
 */
export interface CartItem {
  id: number;
  cart: number | Cart;
  variant: number | ProductVariant;
  quantity: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items".
 */
export interface OrderItem {
  id: number;
  order: number | Order;
  product?: (number | null) | Product;
  variant?: (number | null) | ProductVariant;
  skuSnapshot: string;
  productNameSnapshot: string;
  sizeSnapshot?: string | null;
  colorSnapshot?: string | null;
  imageUrlSnapshot?: string | null;
  quantity: number;
  unitPricePaise: number;
  unitDiscountPaise: number;
  lineSubtotalPaise: number;
  lineDiscountPaise: number;
  lineTaxPaise: number;
  lineTotalPaise: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-status-events".
 */
export interface OrderStatusEvent {
  id: number;
  order: number | Order;
  fromStatus?:
    | ('pending_payment' | 'confirmed' | 'processing' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'returned')
    | null;
  toStatus:
    'pending_payment' | 'confirmed' | 'processing' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
  eventType: string;
  actorType: 'system' | 'customer' | 'admin' | 'carrier';
  actorId?: string | null;
  reason?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-reservations".
 */
export interface InventoryReservation {
  id: number;
  order: number | Order;
  variant: number | ProductVariant;
  quantity: number;
  status: 'active' | 'committed' | 'released' | 'expired';
  expiresAt: string;
  releasedAt?: string | null;
  committedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts".
 */
export interface PaymentAttempt {
  id: number;
  order: number | Order;
  provider: 'razorpay' | 'cashfree' | 'manual_cod';
  paymentMethod: 'upi' | 'card' | 'netbanking' | 'wallet' | 'cod';
  providerOrderId?: string | null;
  providerPaymentId?: string | null;
  idempotencyKey: string;
  amountPaise: number;
  currency: 'INR';
  status: 'created' | 'pending' | 'authorized' | 'paid' | 'failed' | 'expired' | 'cancelled';
  failureCode?: string | null;
  failureMessage?: string | null;
  initiatedAt: string;
  completedAt?: string | null;
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-webhook-events".
 */
export interface PaymentWebhookEvent {
  id: number;
  provider: 'razorpay' | 'cashfree';
  externalEventId: string;
  kind: string;
  signatureVerified: boolean;
  payloadRedacted?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'received' | 'processed' | 'ignored' | 'failed';
  processedAt?: string | null;
  errorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon-redemptions".
 */
export interface CouponRedemption {
  id: number;
  coupon: number | Coupon;
  customer: number | Customer;
  order: number | Order;
  amountPaise: number;
  status: 'allocated' | 'redeemed' | 'released';
  allocatedAt: string;
  redeemedAt?: string | null;
  releasedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'catalog-attribute-definitions';
        value: number | CatalogAttributeDefinition;
      } | null)
    | ({
        relationTo: 'catalog-attribute-options';
        value: number | CatalogAttributeOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'inventory';
        value: number | Inventory;
      } | null)
    | ({
        relationTo: 'inventory-movements';
        value: number | InventoryMovement;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-addresses';
        value: number | CustomerAddress;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'wishlist-items';
        value: number | WishlistItem;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'cart-items';
        value: number | CartItem;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'order-items';
        value: number | OrderItem;
      } | null)
    | ({
        relationTo: 'order-status-events';
        value: number | OrderStatusEvent;
      } | null)
    | ({
        relationTo: 'inventory-reservations';
        value: number | InventoryReservation;
      } | null)
    | ({
        relationTo: 'payment-attempts';
        value: number | PaymentAttempt;
      } | null)
    | ({
        relationTo: 'payment-webhook-events';
        value: number | PaymentWebhookEvent;
      } | null)
    | ({
        relationTo: 'coupon-redemptions';
        value: number | CouponRedemption;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  kind?: T;
  photographerCredit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  image?: T;
  description?: T;
  sortOrder?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  heroImage?: T;
  occasion?: T;
  isPublished?: T;
  sortOrder?: T;
  startsAt?: T;
  endsAt?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-attribute-definitions_select".
 */
export interface CatalogAttributeDefinitionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  scope?: T;
  valueType?: T;
  filterable?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-attribute-options_select".
 */
export interface CatalogAttributeOptionsSelect<T extends boolean = true> {
  attribute?: T;
  code?: T;
  label?: T;
  swatchHex?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  status?: T;
  primaryCategory?: T;
  categories?: T;
  collections?: T;
  jewelryDetails?:
    | T
    | {
        brand?: T;
        material?: T;
        plating?: T;
        stoneType?: T;
      };
  styleTags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  occasions?:
    | T
    | {
        occasion?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  careInstructions?: T;
  isReturnable?: T;
  returnWindowDays?: T;
  weightGrams?: T;
  hsnCode?: T;
  taxClass?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        variant?: T;
        caption?: T;
        sortOrder?: T;
        id?: T;
      };
  isFeatured?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  variants?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  sku?: T;
  optionSignature?: T;
  sizeCode?: T;
  colorCode?: T;
  finishCode?: T;
  optionValues?:
    | T
    | {
        attribute?: T;
        option?: T;
        id?: T;
      };
  pricePaise?: T;
  compareAtPricePaise?: T;
  costPaise?: T;
  status?: T;
  barcode?: T;
  weightGrams?: T;
  image?: T;
  maxPerOrder?: T;
  inventory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  variant?: T;
  onHand?: T;
  reserved?: T;
  available?: T;
  reorderPoint?: T;
  stockStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-movements_select".
 */
export interface InventoryMovementsSelect<T extends boolean = true> {
  variant?: T;
  quantityDelta?: T;
  reason?: T;
  referenceType?: T;
  referenceId?: T;
  performedBy?: T;
  note?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phoneNumber?: T;
  phoneVerified?: T;
  status?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses_select".
 */
export interface CustomerAddressesSelect<T extends boolean = true> {
  customer?: T;
  recipientName?: T;
  phoneNumber?: T;
  line1?: T;
  line2?: T;
  landmark?: T;
  city?: T;
  stateCode?: T;
  pincode?: T;
  countryCode?: T;
  addressType?: T;
  isDefault?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  customer?: T;
  name?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist-items_select".
 */
export interface WishlistItemsSelect<T extends boolean = true> {
  wishlist?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  customer?: T;
  status?: T;
  currency?: T;
  coupon?: T;
  convertedOrder?: T;
  items?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-items_select".
 */
export interface CartItemsSelect<T extends boolean = true> {
  cart?: T;
  variant?: T;
  quantity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  discountType?: T;
  discountValue?: T;
  maxDiscountPaise?: T;
  startsAt?: T;
  endsAt?: T;
  status?: T;
  applicableProducts?: T;
  applicableCategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  promotion?: T;
  status?: T;
  usageLimit?: T;
  perCustomerLimit?: T;
  minimumCartPaise?: T;
  startsAt?: T;
  endsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  cart?: T;
  idempotencyKey?: T;
  requestHash?: T;
  status?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  paymentMethod?: T;
  currency?: T;
  itemsSubtotalPaise?: T;
  discountPaise?: T;
  shippingPaise?: T;
  taxPaise?: T;
  codFeePaise?: T;
  grandTotalPaise?: T;
  shippingAddressSnapshot?: T;
  billingAddressSnapshot?: T;
  pricingBreakdown?: T;
  couponCodeSnapshot?: T;
  customerNote?: T;
  exceptionCode?: T;
  placedAt?: T;
  confirmedAt?: T;
  cancelledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-items_select".
 */
export interface OrderItemsSelect<T extends boolean = true> {
  order?: T;
  product?: T;
  variant?: T;
  skuSnapshot?: T;
  productNameSnapshot?: T;
  sizeSnapshot?: T;
  colorSnapshot?: T;
  imageUrlSnapshot?: T;
  quantity?: T;
  unitPricePaise?: T;
  unitDiscountPaise?: T;
  lineSubtotalPaise?: T;
  lineDiscountPaise?: T;
  lineTaxPaise?: T;
  lineTotalPaise?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-status-events_select".
 */
export interface OrderStatusEventsSelect<T extends boolean = true> {
  order?: T;
  fromStatus?: T;
  toStatus?: T;
  eventType?: T;
  actorType?: T;
  actorId?: T;
  reason?: T;
  metadata?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-reservations_select".
 */
export interface InventoryReservationsSelect<T extends boolean = true> {
  order?: T;
  variant?: T;
  quantity?: T;
  status?: T;
  expiresAt?: T;
  releasedAt?: T;
  committedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-attempts_select".
 */
export interface PaymentAttemptsSelect<T extends boolean = true> {
  order?: T;
  provider?: T;
  paymentMethod?: T;
  providerOrderId?: T;
  providerPaymentId?: T;
  idempotencyKey?: T;
  amountPaise?: T;
  currency?: T;
  status?: T;
  failureCode?: T;
  failureMessage?: T;
  initiatedAt?: T;
  completedAt?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-webhook-events_select".
 */
export interface PaymentWebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  externalEventId?: T;
  kind?: T;
  signatureVerified?: T;
  payloadRedacted?: T;
  status?: T;
  processedAt?: T;
  errorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupon-redemptions_select".
 */
export interface CouponRedemptionsSelect<T extends boolean = true> {
  coupon?: T;
  customer?: T;
  order?: T;
  amountPaise?: T;
  status?: T;
  allocatedAt?: T;
  redeemedAt?: T;
  releasedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings".
 */
export interface ShippingSetting {
  id: number;
  freeShippingAbovePaise?: number | null;
  standardFeePaise?: number | null;
  codEnabled: boolean;
  codFeePaise?: number | null;
  handlingDays?: number | null;
  /**
   * Development fallback only. Replace with a carrier serviceability check before production.
   */
  localServiceabilityMode: 'disabled' | 'development_all_india';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings_select".
 */
export interface ShippingSettingsSelect<T extends boolean = true> {
  freeShippingAbovePaise?: T;
  standardFeePaise?: T;
  codEnabled?: T;
  codFeePaise?: T;
  handlingDays?: T;
  localServiceabilityMode?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}